### ISSUE TITLE
OPMGAZDSANJ SPIFDHNJAOL SO ANGRY!!!!!!

### ISSUE THREAD

**Issue by GentleSphee** [OverlordOE/Neija#22]
**Describe the feature you'd like**

NEFRFDA THE BOT HGE TOOOK ALLL YM MONYEHY AIM SHAKING AN CRYINGA RN
**Additional context**

**Comment by GentleSphee** [comment]
OMFGJH HE IAS CHEWAAtiong in blacfjkack

pl,s giv  all my 100r0 bucks baclk

**Comment by OverlordOE** [comment]
get some better luck :)

**Comment by GentleSphee** [comment]
DONT ANJNJGF CLOPSE IYT !### !
